error: major refactoring makes it easier to add error types and strings
Using std::map instead of array for mapping error type numbers to error
strings.

Renamed print_cmd_errmsg to print_errmsg and use std::vector to pass
string arguments, rather than pass them discretely.